function [] = run_everything_s3_1_n()

%run all model parameter optimisations
%choiceFile, outcomeFile, startFile,subFile, sRun, trialsq,outputFile,choiceRule

%run S3 study all trials

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_1.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_2.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_2.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',1);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_2.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',2);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_2.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',3);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_3.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',1);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_3.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',2);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_3.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'matlab/output/S3/real/S3_',3);

runAllSubjects_n('scripts/input/S3/choices_S3_1.csv',...
    'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_4.csv',...
    'scripts/input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);