function [] = run_everything_simul_s3_1_par()


%runAllSubjects_Simul_n( choiceFile, outcomeFile, ...
%   startFile, matlab/outputFile, sRun, trialsq, choiceRule)

runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
	'scripts/input/S3/outcomes_S3_1.csv',...
    'scripts/input/startValues_1.csv',...
	'matlab/output/S3/simul_par/Simul_S3_',1,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_2.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_2.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,2);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_2.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,3);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,2);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,3);

% runAllSubjects_Simul_n('matlab/output/S3/simul_par/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
%     'scripts/input/startValues_4.csv',...
% 	'matlab/output/S3/simul_par/Simul_S3_',1,1,1);