function [] = run_everything_simul()


%runAllSubjects_Simul( choiceFile, outcomeFile, ...
%   startFile, outputFile, sRun, trialsq, choiceRule)

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_1.csv',...
	'output/S3/simul/Simul_S3_',1,1,1);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
	'output/S3/simul/Simul_S3_',1,1,1);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
	'output/S3/simul/Simul_S3_',1,1,2);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
	'output/S3/simul/Simul_S3_',1,1,3);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
	'output/S3/simul/Simul_S3_',1,1,1);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
	'output/S3/simul/Simul_S3_',1,1,2);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
	'output/S3/simul/Simul_S3_',1,1,3);

runAllSubjects_Simul('output/S3/simul/M4_all/Simul_S3_M4',...
	'input/S3/outcomes_S3_1.csv',...
    'input/startValues_4.csv',...
	'output/S3/simul/Simul_S3_',1,1,1);