function [] = run_everything()

%run all model parameter optimisations
%choiceFile, outcomeFile, startFile,subFile,outputFile,choiceRule

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_1.csv',...
    'input/subjects.csv',...
    'output/filename_',1);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_2.csv',...
    'input/subjects.csv',...
    'output/filename_',1);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_2.csv',...
    'input/subjects.csv',...
    'output/filename_',2);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_2.csv',...
    'input/subjects.csv',...
    'output/filename_',3);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_3.csv',...
    'input/subjects.csv',...
    'output/filename_',1);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_3.csv',...
    'input/subjects.csv',...
    'output/filename_',2);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_3.csv',...
    'input/subjects.csv',...
    'output/filename_',3);

runAllSubjects('input/choices.csv',...
    'input/outcomes.csv',...
    'input/startValues_4.csv',...
    'input/subjects.csv',...
    'output/filename_',1);