function [] = run_everything_simul_s3_2_n()


%runAllSubjects_Simul_n( choiceFile, outcomeFile, ...
%   startFile, matlab/outputFile, sRun, trialsq, choiceRule)

% runAllSubjects_Simul_n('matlab/output/S3/simul/M1_all/Simul_S3_M1',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_1.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul/M2_all/Simul_S3_M2',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_2.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul/M2_all/Simul_S3_M22',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_2.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,2);

runAllSubjects_Simul_n('matlab/output/S3/simul/M2_all/Simul_S3_M23',...
	'scripts/input/S3/outcomes_S3_2.csv',...
    'scripts/input/startValues_2.csv',...
	'matlab/output/S3/simul/Simul_S3_',2,1,3);

% runAllSubjects_Simul_n('matlab/output/S3/simul/M3_all/Simul_S3_M3',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,1);

% runAllSubjects_Simul_n('matlab/output/S3/simul/M3_all/Simul_S3_M32',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,2);


% runAllSubjects_Simul_n('matlab/output/S3/simul/M3_all/Simul_S3_M33',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_3.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,3);

% runAllSubjects_Simul_n('matlab/output/S3/simul/M4_all/Simul_S3_M4',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
%     'scripts/input/startValues_4.csv',...
% 	'matlab/output/S3/simul/Simul_S3_',2,1,1);