function [] = run_everything()

%run all model parameter optimisations
%choiceFile, outcomeFile, startFile,subFile, sRun, trialsq,outputFile,choiceRule

%run S3 study all trials

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_1.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',2);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_2.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',3);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',2);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_3.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',3);

runAllSubjects('input/S3/choices_S3_1.csv',...
    'input/S3/outcomes_S3_1.csv',...
    'input/startValues_4.csv',...
    'input/S3/subjects_S3.csv',1,1,...
    'output/S3/real/S3_',1);