function [] = all_qValue_n()


%function [] = runQValue_n(parameterFile, outcomeFile, choiceFile,...
%      filenameQ,filenameP,choiceRule,)

% runQValue_n('scripts/input/S3/S3_M1_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M1_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M1_all_1.csv',1);

% runQValue_n('scripts/input/S3/S3_M21_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M21_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M21_all_1.csv',1);

% runQValue_n('scripts/input/S3/S3_M22_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M22_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M22_all_1.csv',2);

% runQValue_n('scripts/input/S3/S3_M23_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M23_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M23_all_1.csv',3);

% runQValue_n('scripts/input/S3/S3_M31_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M31_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M31_all_1.csv',1);

% runQValue_n('scripts/input/S3/S3_M32_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M32_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M32_all_1.csv',2);

% runQValue_n('scripts/input/S3/S3_M33_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M33_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M33_all_1.csv',3);

% runQValue_n('scripts/input/S3/S3_M4_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'scripts/input/S3/choices_S3_1.csv',...
% 	'output/S3/q-value/S3_qVal_M4_all_1.csv',...
% 	'output/S3/probs/S3_Prob_M4_all_1.csv',1);

runQValue_n('scripts/input/S3/S3_M1_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'scripts/input/S3/choices_S3_2.csv',...
	'output/S3/q-value/S3_qVal_M1_all_2.csv',...
	'output/S3/probs/S3_Prob_M1_all_2.csv',1);

runQValue_n('scripts/input/S3/S3_M21_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'scripts/input/S3/choices_S3_2.csv',...
	'output/S3/q-value/S3_qVal_M21_all_2.csv',...
	'output/S3/probs/S3_Prob_M21_all_2.csv',1);

% runQValue_n('scripts/input/S3/S3_M22_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'scripts/input/S3/choices_S3_2.csv',...
% 	'output/S3/q-value/S3_qVal_M22_all_2.csv',...
% 	'output/S3/probs/S3_Prob_M22_all_2.csv',2);

% runQValue_n('scripts/input/S3/S3_M23_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'scripts/input/S3/choices_S3_2.csv',...
% 	'output/S3/q-value/S3_qVal_M23_all_2.csv',...
% 	'output/S3/probs/S3_Prob_M23_all_2.csv',3);

runQValue_n('scripts/input/S3/S3_M31_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'scripts/input/S3/choices_S3_2.csv',...
	'output/S3/q-value/S3_qVal_M31_all_2.csv',...
	'output/S3/probs/S3_Prob_M31_all_2.csv',1);

% runQValue_n('scripts/input/S3/S3_M32_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'scripts/input/S3/choices_S3_2.csv',...
% 	'output/S3/q-value/S3_qVal_M32_all_2.csv',...
% 	'output/S3/probs/S3_Prob_M32_all_2.csv',2);

% runQValue_n('scripts/input/S3/S3_M33_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'scripts/input/S3/choices_S3_2.csv',...
% 	'output/S3/q-value/S3_qVal_M33_all_2.csv',...
% 	'output/S3/probs/S3_Prob_M33_all_2.csv',3);

runQValue_n('scripts/input/S3/S3_M4_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'scripts/input/S3/choices_S3_2.csv',...
	'output/S3/q-value/S3_qVal_M4_all_2.csv',...
	'output/S3/probs/S3_Prob_M4_all_2.csv',1);