function [] = all_qValue()


%runQValue(parameterFile, outcomeFile, choiceFile,...
%    choiceRule, outputFile, outputSummaryFile)

% runQValue('PhD/DMDET_Analysis/Input/2P_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',1,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q2P/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/3P_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',1,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q3P/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/4P_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',1,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q4P/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/5P_ml.csv',...
%  	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',1,...
%  	'PhD/DMDET_Analysis/ME_data_BE/q5P/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% 
% runQValue('PhD/DMDET_Analysis/Input/2Pe_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',2,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q2P_e/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/3Pe_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',2,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q3P_e/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/4Pe_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',2,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q4P_e/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');
% runQValue('PhD/DMDET_Analysis/Input/5Pe_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',...
% 	'PhD/DMDET_Analysis/Input/choices_BE.csv',2,...
% 	'PhD/DMDET_Analysis/ME_data_BE/q5P_e/Simul_BE_q',...
% 	'PhD/DMDET_Analysis/ME_data_BE/qSummary/Summary_q');