function [] = simul_everything_be()


%runSimul(parameterFile, outcomeFile,outputFile, nrIt,sRun)

runSimul_be('scripts/input/BE/BE_M1_all.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M1_all/Simul_BE_',30,0,1);
runSimul_be('scripts/input/BE/BE_M2_all.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M2_all/Simul_BE_',30,0,1);
runSimul_be('scripts/input/BE/BE_M3_all.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M3_all/Simul_BE_',30,0,1);
runSimul_be('scripts/input/BE/BE_M4_all.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M4_all/Simul_BE_',30,0,1);

runSimul_be('scripts/input/BE/BE_M1_dyn.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M1_dyn/Simul_BE_',30,0,3);
runSimul_be('scripts/input/BE/BE_M2_dyn.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M2_dyn/Simul_BE_',30,0,3);
runSimul_be('scripts/input/BE/BE_M3_dyn.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M3_dyn/Simul_BE_',30,0,3);
runSimul_be('scripts/input/BE/BE_M4_dyn.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M4_dyn/Simul_BE_',30,0,3);

runSimul_be('scripts/input/BE/BE_M1_sta.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M1_sta/Simul_BE_',30,0,2);
runSimul_be('scripts/input/BE/BE_M2_sta.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M2_sta/Simul_BE_',30,0,2);
runSimul_be('scripts/input/BE/BE_M3_sta.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M3_sta/Simul_BE_',30,0,2);
runSimul_be('scripts/input/BE/BE_M4_sta.csv',...
	'scripts/input/BE/outcomes_BE.csv',...
	'output/BE/simul/M4_sta/Simul_BE_',30,0,2);