function [] = simul_everything_s3_2()


%runSimul(parameterFile, outcomeFile,outputFile, nrIt,sRun)

%runSimul('scripts/input/S3/S3_M1_all_2.csv',...
%	'scripts/input/S3/outcomes_S3_2.csv',...
%	'output/S3/simul/M1_all/Simul_S3_',30,2,1);
%runSimul('scripts/input/S3/S3_M21_all_2.csv',...
%	'scripts/input/S3/outcomes_S3_2.csv',...
%	'output/S3/simul/M2_all/Simul_S3_',30,2,1);
runSimul('scripts/input/S3/S3_M31_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'output/S3/simul/M3_all/Simul_S3_',30,2,1);
runSimul('scripts/input/S3/S3_M4_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'output/S3/simul/M4_all/Simul_S3_',30,2,1);

% runSimul('scripts/input/S3/S3_M1_dyn_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M1_dyn/Simul_S3_',30,2,3);
% runSimul('scripts/input/S3/S3_M2_dyn_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M2_dyn/Simul_S3_',30,2,3);
% runSimul('scripts/input/S3/S3_M3_dyn_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M3_dyn/Simul_S3_',30,2,3);
% runSimul('scripts/input/S3/S3_M4_dyn_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M4_dyn/Simul_S3_',30,2,3);

% runSimul('scripts/input/S3/S3_M1_sta_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M1_sta/Simul_S3_',30,2,2);
% runSimul('scripts/input/S3/S3_M2_sta_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M2_sta/Simul_S3_',30,2,2);
% runSimul('scripts/input/S3/S3_M3_sta_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M3_sta/Simul_S3_',30,2,2);
% runSimul('scripts/input/S3/S3_M4_sta_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M4_sta/Simul_S3_',30,2,2);