function [] = simul_everything_s3_1_n()


%runSimul_n(parameterFile, outcomeFile,outputFile, nrIt,sRun, choiceRule)

% runSimul_n('scripts/input/S3/S3_M1_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'output/S3/simul/M1_all/Simul_S3_',30,1,1,1);
% runSimul_n('scripts/input/S3/S3_M2_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'output/S3/simul/M2_all/Simul_S3_',30,1,1,1);
% runSimul_n('scripts/input/S3/S3_M22_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'matlab/output/S3/simul/M2_all/Simul_S3_',30,1,1,2);
runSimul_n('scripts/input/S3/S3_M23_all_1.csv',...
	'scripts/input/S3/outcomes_S3_1.csv',...
	'output/S3/simul/M2_all/Simul_S3_',30,1,1,3);
% runSimul_n('scripts/input/S3/S3_M3_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'output/S3/simul/M3_all/Simul_S3_',30,1,1,1);
% runSimul_n('scripts/input/S3/S3_M32_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'matlab/output/S3/simul/M3_all/Simul_S3_',30,1,1,2);
% runSimul_n('scripts/input/S3/S3_M33_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'matlab/output/S3/simul/M3_all/Simul_S3_',30,1,1,3);
% runSimul_n('scripts/input/S3/S3_M4_all_1.csv',...
% 	'scripts/input/S3/outcomes_S3_1.csv',...
% 	'output/S3/simul/M4_all/Simul_S3_',30,1,1,1);