function [] = simul_everything_s3_2_n()


%runSimul_n(parameterFile, outcomeFile, outputFile, nrIt,sRun,trialsq, choiceRule)

% runSimul_n('scripts/input/S3/S3_M1_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M1_all/Simul_S3_',30,2,1,1);
% runSimul_n('scripts/input/S3/S3_M2_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M2_all/Simul_S3_',30,2,1,1);
% runSimul_n('scripts/input/S3/S3_M22_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'matlab/output/S3/simul/M2_all/Simul_S3_',30,2,1,2);
runSimul_n('scripts/input/S3/S3_M23_all_2.csv',...
	'scripts/input/S3/outcomes_S3_2.csv',...
	'output/S3/simul/M2_all/Simul_S3_',30,2,1,3);
% runSimul_n('scripts/input/S3/S3_M3_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M3_all/Simul_S3_',30,2,1,1);
% runSimul_n('scripts/input/S3/S3_M32_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'matlab/output/S3/simul/M3_all/Simul_S3_',30,2,1,2);
% runSimul_n('scripts/input/S3/S3_M33_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'matlab/output/S3/simul/M3_all/Simul_S3_',30,2,1,3);
% runSimul_n('scripts/input/S3/S3_M4_all_2.csv',...
% 	'scripts/input/S3/outcomes_S3_2.csv',...
% 	'output/S3/simul/M4_all/Simul_S3_',30,2,1,1);