function [] = simul_everything_s3_par()


%runSimul_n(parameterFile, outcomeFile,outputFile, nrIt,sRun, choiceRule)

runSimul_n('scripts/input/S3/S3_M41_par_all_1.csv',...
	'scripts/input/S3/outcomes_S3_1.csv',...
	'output/S3/simul/M4_all_par/Simul_S3_',30,1,1,1);

runSimul_n('scripts/input/S3/S3_M41_par_all_1.csv',...
	'scripts/input/S3/outcomes_S3_1.csv',...
	'output/S3/simul/M4_all_par/Simul_S3_',30,2,1,1);