function [] = simul_everything()


%runSimul(parameterFile, outcomeFile, nrIt,choiceRule, outputFile)

%runSimul('PhD/DMDET_Analysis/Input/2P_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,1,...
%	'PhD/DMDET_Analysis/Simul_data_BE/2P/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/3P_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,1,...
% 	'PhD/DMDET_Analysis/Simul_data_BE/3P/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/4P_ml.csv',...
% 	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,1,...
% 	'PhD/DMDET_Analysis/Simul_data_BE/4P/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/5P_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,1,...
% 	'PhD/DMDET_Analysis/Simul_data_BE/5P/Simul_BE_');

%runSimul('PhD/DMDET_Analysis/Input/2Pe_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,2,...
%	'PhD/DMDET_Analysis/Simul_data_BE/2P_e/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/3Pe_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,2,...
%	'PhD/DMDET_Analysis/Simul_data_BE/3P_e/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/4Pe_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,2,...
%	'PhD/DMDET_Analysis/Simul_data_BE/4P_e/Simul_BE_');
%runSimul('PhD/DMDET_Analysis/Input/5Pe_ml.csv',...
%	'PhD/DMDET_Analysis/Input/outcomes_BE.csv',10,2,...
%	'PhD/DMDET_Analysis/Simul_data_BE/5P_e/Simul_BE_');