function [] = simul_everything_ep()


%runSimul(parameterFile, outcomeFile,outputFile, nrIt,sRun)

runSimul('scripts/input/EP/EP_M1_all.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M1_all/Simul_EP_',30,0,1);
runSimul('scripts/input/EP/EP_M2_all.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M2_all/Simul_EP_',30,0,1);
runSimul('scripts/input/EP/EP_M3_all.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M3_all/Simul_EP_',30,0,1);
runSimul('scripts/input/EP/EP_M4_all.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M4_all/Simul_EP_',30,0,1);

runSimul('scripts/input/EP/EP_M1_dyn.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M1_dyn/Simul_EP_',30,0,3);
runSimul('scripts/input/EP/EP_M2_dyn.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M2_dyn/Simul_EP_',30,0,3);
runSimul('scripts/input/EP/EP_M3_dyn.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M3_dyn/Simul_EP_',30,0,3);
runSimul('scripts/input/EP/EP_M4_dyn.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M4_dyn/Simul_EP_',30,0,3);

runSimul('scripts/input/EP/EP_M1_sta.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M1_sta/Simul_EP_',30,0,2);
runSimul('scripts/input/EP/EP_M2_sta.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M2_sta/Simul_EP_',30,0,2);
runSimul('scripts/input/EP/EP_M3_sta.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M3_sta/Simul_EP_',30,0,2);
runSimul('scripts/input/EP/EP_M4_sta.csv',...
	'scripts/input/EP/outcomes_EP.csv',...
	'output/EP/simul/M4_sta/Simul_EP_',30,0,2);