function [] = simul_everything()


%runSimul(parameterFile, outcomeFile,outputFile, nrIt, choiceRule)

runSimul('input/M1.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,1);
runSimul('input/M21.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,1);
runSimul('input/M22.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,2);
runSimul('input/M23.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,3);
runSimul('input/M31_csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,1);
runSimul('input/M32.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,2);
runSimul('input/M33.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,3);
runSimul('input/M4.csv',...
	'input/outcomes.csv',...
	'output/Simul_',30,1);